// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tree

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Constant struct {
	_tab flatbuffers.Table
}

func GetRootAsConstant(buf []byte, offset flatbuffers.UOffsetT) *Constant {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Constant{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Constant) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Constant) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Constant) Value() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Constant) MutateValue(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func ConstantStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ConstantAddValue(builder *flatbuffers.Builder, value float64) {
	builder.PrependFloat64Slot(0, value, 0.0)
}
func ConstantEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
