// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tree

type Node = byte
const (
	NodeNONE Node = 0
	NodeBinOp Node = 1
	NodeConstant Node = 2
)

var EnumNamesNode = map[Node]string{
	NodeNONE:"NONE",
	NodeBinOp:"BinOp",
	NodeConstant:"Constant",
}

