// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tree

type Op = int8
const (
	OpAdd Op = 0
	OpSubtract Op = 1
	OpMultiply Op = 2
	OpDivide Op = 3
)

var EnumNamesOp = map[Op]string{
	OpAdd:"Add",
	OpSubtract:"Subtract",
	OpMultiply:"Multiply",
	OpDivide:"Divide",
}

