// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package tree

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Root struct {
	_tab flatbuffers.Table
}

func GetRootAsRoot(buf []byte, offset flatbuffers.UOffsetT) *Root {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Root{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Root) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Root) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Root) ExprType() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Root) MutateExprType(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func (rcv *Root) Expr(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func RootStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func RootAddExprType(builder *flatbuffers.Builder, exprType byte) {
	builder.PrependByteSlot(0, exprType, 0)
}
func RootAddExpr(builder *flatbuffers.Builder, expr flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(expr), 0)
}
func RootEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
